version = 3

exclude_patterns = [
    "**/public/",
    "**/git-tools/",
    "**/messages/",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs", "browser"]
  dialect = "typescript"      # TypeScript 사용 설정
  plugins = ["react"]         # React 플러그인 사용
