version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]         # React 플러그인 사용
  environment = ["nodejs", "browser"]
  dependency_file_paths = [
    "app/"
  ]
